name: Publish Package
on:
 release:
   types: [released]
 workflow_dispatch:
jobs:
 build:
   runs-on: ubuntu-latest
   permissions:
     contents: read
     id-token: write
   steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-node@v3
       with:
         node-version: '18.14.0'
         registry-url: 'https://nexus.adito.cloud/repository/xrm/'
         scope: '@aditosoftware'
         always-auth: true

     - run: npm set //nexus.adito.cloud/repository/xrm/:_auth ${{ secrets.NEXUS_NPM_TOKEN }} && npm config delete //nexus.adito.cloud/repository/xrm/:_authToken

     - run: npm run install_and_test

     - run: npm publish
